name: chap08
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"







dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  flutter_secure_storage: ^4.1.0
  

  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:
  assets:
    - assets/
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
